apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-streamlit-app
  labels:
    app: llm-streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-streamlit-app
  template:
    metadata:
      labels:
        app: llm-streamlit-app
    spec:
      containers:
      - name: llm-streamlit-app
        image: llm-streamlit-app:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501
        env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: rag-secrets
                  key: GROQ_API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: llm-streamlit-app-svc
spec:
  selector:
    app: llm-streamlit-app
  type: LoadBalancer
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30053

